version: "3.9"

services:
  nginx:
    container_name: infisical-nginx
    image: nginx
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:14-alpine
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: infisical
      POSTGRES_USER: infisical
      POSTGRES_DB: infisical

  redis:
    image: redis
    container_name: infisical-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379
    volumes:
      - redis_data:/data

  db-migration:
    container_name: infisical-db-migration
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DB_CONNECTION_URI=postgres://infisical:infisical@db/infisical?sslmode=disable
    command: npm run migration:latest
    volumes:
      - ./backend/src:/app/src

  backend:
    container_name: infisical-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - 4000
    environment:
      - NODE_ENV=production
      - DB_CONNECTION_URI=postgres://infisical:infisical@db/infisical?sslmode=disable
      - TELEMETRY_ENABLED=true
    volumes:
      - ./backend/src:/app/src

  frontend:
    container_name: infisical-frontend
    restart: unless-stopped
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src/ # mounted whole src to avoid missing reload on new files
      - ./frontend/public:/app/public
    env_file: .env
    environment:
      - NEXT_PUBLIC_ENV=production
      - INFISICAL_TELEMETRY_ENABLED=true

volumes:
  postgres-data:
    driver: local
  redis_data:
    driver: local
